### ISSUE TITLE
RFE: do not flag HTTP status range uses

### ISSUE THREAD

**Issue by scop** [sashamelentyev/usestdlibvars#89]
When a literal HTTP status code is used as a range, such as `res.statusCode >= 400` or `res.statusCode < 500`, in my opinion it is actually better to use a numeric constant instead of the stdlib named one. Conditions like `res.statusCode >= http.StatusBadRequest` or are harder to understand and just cognitive burden when the intent is to check whether a code is within a specified range. For equality and inequality comparisons  the named ones are good, no problem with that.

**Comment by sashamelentyev** [comment]
@scop hello! Thank you!
Fixed it in #90
